// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwjmyqismejztjmtzlsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3am15cWlzbWVqenRqbXR6bHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjYwMjIsImV4cCI6MjA3MDM0MjAyMn0.iLpGOn_SpzsukIlEqICSCchZcDrm14iKpidRnPO4lo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});